package agent

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"

	"github.com/DonScott603/gogoclaw/internal/config"
	"golang.org/x/term"
)

// ProviderSummary holds configuration for a single LLM provider.
type ProviderSummary struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	BaseURL string `json:"base_url"`
	KeyEnv  string `json:"api_key_env"`
	Model   string `json:"model"`
}

// BootstrapSummary is the JSON output parsed from the LLM's bootstrap response.
type BootstrapSummary struct {
	UserName          string `json:"user_name"`
	AgentName         string `json:"agent_name"`
	Personality       string `json:"personality"`
	WorkDomain        string `json:"work_domain"`
	PIIMode           string `json:"pii_mode"`
	ProviderType      string `json:"provider_type"`
	ProviderBaseURL   string `json:"provider_base_url"`
	ProviderKeyEnv    string `json:"provider_api_key_env"`
	ProviderModel     string `json:"provider_model"`
	TelegramEnabled   bool   `json:"telegram_enabled"`
	TelegramToken     string `json:"telegram_token_env"`
	RESTEnabled       bool   `json:"rest_enabled"`
	RESTPort          int    `json:"rest_port"`
	RESTKeyEnv        string `json:"rest_api_key_env"`
	TelegramAllowlist []string `json:"telegram_allowed_users,omitempty"`

	// Providers holds multiple provider configs. If populated, these take
	// precedence over the single-provider fields above. The first entry is
	// the primary provider.
	Providers []ProviderSummary `json:"providers,omitempty"`
}

// applyDefaults fills zero-value fields with sensible defaults.
func (s *BootstrapSummary) applyDefaults() {
	if s.AgentName == "" {
		s.AgentName = "GoGoClaw Assistant"
	}
	if s.Personality == "" {
		s.Personality = "professional"
	}
	if s.PIIMode == "" {
		s.PIIMode = "disabled"
	}
	if s.ProviderType == "" {
		s.ProviderType = "openai_compatible"
	}
	if s.ProviderBaseURL == "" {
		switch s.ProviderType {
		case "openai":
			s.ProviderBaseURL = "https://api.openai.com/v1"
		case "ollama":
			s.ProviderBaseURL = "http://localhost:11434/v1"
		default:
			s.ProviderBaseURL = "https://api.openai.com/v1"
		}
	}
	if s.ProviderKeyEnv == "" && s.ProviderType == "openai" {
		s.ProviderKeyEnv = "OPENAI_API_KEY"
	}
	if s.ProviderModel == "" {
		switch s.ProviderType {
		case "openai":
			s.ProviderModel = "gpt-4o-mini"
		case "ollama":
			s.ProviderModel = "llama3"
		default:
			s.ProviderModel = "gpt-4o-mini"
		}
	}
	if s.RESTPort == 0 {
		s.RESTPort = 8080
	}
	if s.RESTKeyEnv == "" {
		s.RESTKeyEnv = "GOGOCLAW_REST_API_KEY"
	}

	// Apply defaults for each provider in the multi-provider list.
	for i := range s.Providers {
		applyProviderDefaults(&s.Providers[i])
	}

	// If no multi-provider list, synthesize one from single-provider fields.
	if len(s.Providers) == 0 {
		s.Providers = []ProviderSummary{{
			Name:    "default",
			Type:    s.ProviderType,
			BaseURL: s.ProviderBaseURL,
			KeyEnv:  s.ProviderKeyEnv,
			Model:   s.ProviderModel,
		}}
	}
}

// applyProviderDefaults fills zero-value fields on a single ProviderSummary.
func applyProviderDefaults(p *ProviderSummary) {
	if p.Type == "" {
		p.Type = "openai_compatible"
	}
	if p.BaseURL == "" {
		switch p.Type {
		case "openai":
			p.BaseURL = "https://api.openai.com/v1"
		case "ollama":
			p.BaseURL = "http://localhost:11434/v1"
		default:
			p.BaseURL = "https://api.openai.com/v1"
		}
	}
	if p.KeyEnv == "" && p.Type == "openai" {
		p.KeyEnv = "OPENAI_API_KEY"
	}
	if p.Model == "" {
		switch p.Type {
		case "openai":
			p.Model = "gpt-4o-mini"
		case "ollama":
			p.Model = "llama3"
		default:
			p.Model = "gpt-4o-mini"
		}
	}
	if p.Name == "" {
		p.Name = "default"
	}
}

// Sender abstracts the engine.Send method for testing.
type Sender interface {
	Send(ctx context.Context, text string) (string, error)
}

// bootstrapDir pairs a relative path with its permission mode.
type bootstrapDir struct {
	Path string
	Perm os.FileMode
}

// bootstrapDirs are the directories created during Phase 1.
// Directories that may contain sensitive data use 0700.
var bootstrapDirs = []bootstrapDir{
	{"workspace/inbox", 0755},
	{"workspace/outbox", 0755},
	{"workspace/scratch", 0755},
	{"workspace/documents", 0755},
	{"memory/daily", 0700},
	{"audit", 0700},
	{"skills.d", 0755},
	{"agents", 0700},
	{"providers", 0755},
	{"channels", 0755},
	{"mcp", 0755},
}

// templateFiles maps source paths (relative to the config templates dir) to
// destination paths (relative to configDir). Only copied if dest doesn't exist.
// Only includes files not generated by writeBootstrapResults.
var templateFiles = []struct {
	Src string // relative to config templates dir (templates/config/)
	Dst string // relative to configDir
}{
	{"config.yaml", "config.yaml"},
	{"agents/base.md", "agents/base.md"},
}

// IsBootstrapped returns true if the initialized marker file exists.
func IsBootstrapped(configDir string) bool {
	_, err := os.Stat(filepath.Join(configDir, "initialized"))
	return err == nil
}

// ErrSetupCancelled is returned when the user cancels bootstrap.
var ErrSetupCancelled = fmt.Errorf("setup cancelled by user")

// RunBootstrap performs the two-phase bootstrap ritual.
// Phase 1: create directory structure and copy default templates.
// Phase 2: interactive Q&A through the engine to configure identity.
// templatesDir is the root templates/ directory (contains bootstrap.md and config/ subdir).
// stdin/stdout are used for the interactive conversation.
func RunBootstrap(ctx context.Context, sender Sender, configDir string, templatesDir string, stdin io.Reader, stdout io.Writer) error {
	// Phase 1: infrastructure — template files live under templates/config/.
	configTemplatesDir := filepath.Join(templatesDir, "config")
	if err := bootstrapInfrastructure(configDir, configTemplatesDir); err != nil {
		return fmt.Errorf("agent: bootstrap phase 1: %w", err)
	}

	// Single scanner shared across all interactive phases to avoid
	// independent buffering that causes missed input on Windows.
	scanner := bufio.NewScanner(stdin)

	// Phase 2: identity — bootstrap.md lives at templates/bootstrap.md.
	summary, err := bootstrapIdentity(ctx, sender, templatesDir, scanner, stdout)
	if err != nil {
		return fmt.Errorf("agent: bootstrap phase 2: %w", err)
	}

	// Phase 3: collect and set environment variables directly (bypasses LLM).
	if err := collectAndSetEnvVars(summary, scanner, stdout); err != nil {
		return fmt.Errorf("agent: bootstrap env vars: %w", err)
	}

	// Write results.
	if err := writeBootstrapResults(configDir, summary); err != nil {
		return fmt.Errorf("agent: bootstrap write results: %w", err)
	}

	if summary.TelegramEnabled && len(summary.TelegramAllowlist) == 0 {
		fmt.Fprintln(stdout, "Note: Add your Telegram username or user ID to ~/.gogoclaw/channels/telegram.yaml allowed_users before the bot will respond.")
	}

	// Validate the generated config before committing.
	if err := validateBootstrapConfig(configDir, summary, stdout); err != nil {
		return err
	}

	// Create initialized marker.
	marker := filepath.Join(configDir, "initialized")
	if err := atomicWriteFile(marker, []byte("ok\n"), 0644); err != nil {
		return fmt.Errorf("agent: create marker: %w", err)
	}

	// Pause so the user can read env var output before TUI takes over.
	fmt.Fprintln(stdout, "\nBootstrap complete. Press Enter to launch GoGoClaw...")
	scanner.Scan()

	return nil
}

// bootstrapInfrastructure creates directories and copies default templates.
func bootstrapInfrastructure(configDir, templatesDir string) error {
	for _, dir := range bootstrapDirs {
		path := filepath.Join(configDir, dir.Path)
		if err := os.MkdirAll(path, dir.Perm); err != nil {
			return fmt.Errorf("create dir %s: %w", dir.Path, err)
		}
	}

	for _, tf := range templateFiles {
		dst := filepath.Join(configDir, tf.Dst)
		if _, err := os.Stat(dst); err == nil {
			continue // already exists, don't overwrite
		}
		src := filepath.Join(templatesDir, tf.Src)
		data, err := os.ReadFile(src)
		if err != nil {
			// Template missing is not fatal — user may have custom install.
			continue
		}
		dstDir := filepath.Dir(dst)
		if err := os.MkdirAll(dstDir, 0755); err != nil {
			return fmt.Errorf("create dir for %s: %w", tf.Dst, err)
		}
		if err := os.WriteFile(dst, data, 0644); err != nil {
			return fmt.Errorf("write %s: %w", tf.Dst, err)
		}
	}

	return nil
}

// bootstrapIdentity runs the interactive Q&A through the engine.
func bootstrapIdentity(ctx context.Context, sender Sender, templatesDir string, scanner *bufio.Scanner, stdout io.Writer) (*BootstrapSummary, error) {
	tmpl, err := os.ReadFile(filepath.Join(templatesDir, "bootstrap.md"))
	if err != nil {
		return nil, fmt.Errorf("read bootstrap template: %w", err)
	}

	// Send the bootstrap template as the first message.
	resp, err := sender.Send(ctx, string(tmpl))
	if err != nil {
		return nil, fmt.Errorf("engine send: %w", err)
	}

	// Interactive loop: show LLM response, get user input, repeat.
	for {
		fmt.Fprintln(stdout, resp)

		// Check if the response contains a JSON summary block.
		if summary := parseJSONSummary(resp); summary != nil {
			// Ask for user confirmation before proceeding.
			fmt.Fprint(stdout, "\n> ")
			if !scanner.Scan() {
				return nil, fmt.Errorf("unexpected end of input")
			}
			answer := strings.TrimSpace(strings.ToLower(scanner.Text()))
			if answer == "y" || answer == "yes" {
				return summary, nil
			}
			fmt.Fprintln(stdout, "Setup cancelled. Run GoGoClaw again to restart setup.")
			return nil, ErrSetupCancelled
		}

		fmt.Fprint(stdout, "\n> ")
		if !scanner.Scan() {
			return nil, fmt.Errorf("unexpected end of input")
		}
		input := strings.TrimSpace(scanner.Text())
		if input == "" {
			input = "[accept default]"
		}

		resp, err = sender.Send(ctx, input)
		if err != nil {
			return nil, fmt.Errorf("engine send: %w", err)
		}
	}
}

var jsonBlockRe = regexp.MustCompile("(?s)```json\\s*\n(.*?)\n\\s*```")

// parseJSONSummary extracts a BootstrapSummary from ```json fences in text.
// Missing fields get sensible defaults applied.
func parseJSONSummary(text string) *BootstrapSummary {
	matches := jsonBlockRe.FindStringSubmatch(text)
	if len(matches) < 2 {
		return nil
	}

	var summary BootstrapSummary
	if err := json.Unmarshal([]byte(matches[1]), &summary); err != nil {
		return nil
	}

	// Require at least user_name to consider it valid.
	if summary.UserName == "" {
		return nil
	}

	summary.applyDefaults()
	return &summary
}

// writeBootstrapResults generates all config files from the bootstrap summary.
func writeBootstrapResults(configDir string, summary *BootstrapSummary) error {
	if err := writeUserMD(configDir, summary); err != nil {
		return err
	}
	if err := writeIdentityYAML(configDir, summary); err != nil {
		return err
	}
	if err := writeProviderYAMLs(configDir, summary); err != nil {
		return err
	}
	if err := writeAgentBaseYAML(configDir, summary); err != nil {
		return err
	}
	if err := writeRESTChannelYAML(configDir, summary); err != nil {
		return err
	}
	if err := writeTelegramChannelYAML(configDir, summary); err != nil {
		return err
	}
	if err := writeNetworkYAML(configDir, summary); err != nil {
		return err
	}
	return nil
}

func writeUserMD(configDir string, s *BootstrapSummary) error {
	content := fmt.Sprintf("# User Profile\n\nName: %s\nPersonality: %s\nWork Domain: %s\nPII Mode: %s\n",
		s.UserName, s.Personality, s.WorkDomain, s.PIIMode)
	path := filepath.Join(configDir, "agents", "user.md")
	return atomicWriteFile(path, []byte(content), 0644)
}

// writeProviderYAMLs writes a separate YAML file for each provider.
func writeProviderYAMLs(configDir string, s *BootstrapSummary) error {
	for _, p := range s.Providers {
		providerType := p.Type
		if providerType == "openai" {
			providerType = "openai_compatible"
		}

		apiKeyLine := ""
		if p.KeyEnv != "" {
			apiKeyLine = fmt.Sprintf("api_key: ${%s}\n", p.KeyEnv)
		}

		content := fmt.Sprintf("name: %q\ntype: %q\nbase_url: %q\n%sdefault_model: %q\nmax_context_tokens: 8192\ntimeout: 60s\nretry: 1\n",
			p.Name, providerType, p.BaseURL, apiKeyLine, p.Model)

		path := filepath.Join(configDir, "providers", p.Name+".yaml")
		if err := atomicWriteFile(path, []byte(content), 0600); err != nil {
			return fmt.Errorf("write provider %s: %w", p.Name, err)
		}
	}
	return nil
}

func writeAgentBaseYAML(configDir string, s *BootstrapSummary) error {
	// Build provider chain entries.
	var chainLines []string
	for _, p := range s.Providers {
		chainLines = append(chainLines,
			fmt.Sprintf("    - provider: %q\n      timeout: 60s\n      retry: 1", p.Name))
	}
	providerChain := strings.Join(chainLines, "\n")

	content := fmt.Sprintf(`name: %q
system_prompt_file: "base.md"

provider_routing:
  mode: "cloud-only"
  provider_chain:
%s

pii:
  mode: %q

skills:
  always_available: true
  auto_discover: true

context:
  max_history_tokens: 4096
  summarization:
    enabled: true
    threshold_tokens: 3072

memory:
  enabled: true
  top_k: 10
  relevance_threshold: 0.3
  recency_weight: 0.2

shell:
  confirmation: "always"
`, s.AgentName, providerChain, s.PIIMode)

	path := filepath.Join(configDir, "agents", "base.yaml")
	return atomicWriteFile(path, []byte(content), 0644)
}

func writeRESTChannelYAML(configDir string, s *BootstrapSummary) error {
	keyEnv := s.RESTKeyEnv
	if keyEnv == "" {
		keyEnv = "GOGOCLAW_REST_API_KEY"
	}
	content := fmt.Sprintf("name: \"rest\"\nenabled: %t\nlisten: \"127.0.0.1:%d\"\napi_key_env: %q\n",
		s.RESTEnabled, s.RESTPort, keyEnv)

	path := filepath.Join(configDir, "channels", "rest.yaml")
	return atomicWriteFile(path, []byte(content), 0644)
}

func writeTelegramChannelYAML(configDir string, s *BootstrapSummary) error {
	tokenEnv := s.TelegramToken
	if tokenEnv == "" {
		tokenEnv = "GOGOCLAW_TELEGRAM_TOKEN"
	}

	var allowedUsers string
	if len(s.TelegramAllowlist) == 0 {
		allowedUsers = "allowed_users: []"
	} else {
		lines := []string{"allowed_users:"}
		for _, user := range s.TelegramAllowlist {
			lines = append(lines, fmt.Sprintf("  - %q", user))
		}
		allowedUsers = strings.Join(lines, "\n")
	}

	content := fmt.Sprintf("name: \"telegram\"\nenabled: %t\ntoken_env: %q\n%s\npolling_timeout: 10s\n",
		s.TelegramEnabled, tokenEnv, allowedUsers)

	path := filepath.Join(configDir, "channels", "telegram.yaml")
	return atomicWriteFile(path, []byte(content), 0644)
}

func writeNetworkYAML(configDir string, s *BootstrapSummary) error {
	hosts := []string{"localhost", "127.0.0.1"}

	// Extract domains from all provider base URLs and add to allowlist.
	for _, p := range s.Providers {
		if domain := extractDomain(p.BaseURL); domain != "" {
			if !containsStr(hosts, domain) {
				hosts = append(hosts, domain)
			}
		}
	}

	var lines []string
	lines = append(lines, "allowlist:")
	for _, h := range hosts {
		lines = append(lines, fmt.Sprintf("  - %q", h))
	}
	lines = append(lines, "deny_all_others: true")
	lines = append(lines, "log_blocked: true")
	lines = append(lines, "")

	path := filepath.Join(configDir, "network.yaml")
	return atomicWriteFile(path, []byte(strings.Join(lines, "\n")), 0644)
}

// containsStr checks if a string slice contains a value.
func containsStr(ss []string, s string) bool {
	for _, v := range ss {
		if v == s {
			return true
		}
	}
	return false
}

// envVarEntry describes an environment variable to collect from the user.
type envVarEntry struct {
	Name    string
	Purpose string
}

// requiredEnvVars returns the list of env vars that need values based on the summary.
func requiredEnvVars(s *BootstrapSummary) []envVarEntry {
	seen := make(map[string]bool)
	var vars []envVarEntry
	add := func(name, purpose string) {
		if name == "" || seen[name] {
			return
		}
		seen[name] = true
		vars = append(vars, envVarEntry{Name: name, Purpose: purpose})
	}

	for _, p := range s.Providers {
		if p.KeyEnv != "" {
			add(p.KeyEnv, fmt.Sprintf("API key for %s provider (%s)", p.Name, p.Type))
		}
	}
	if s.TelegramEnabled && s.TelegramToken != "" {
		add(s.TelegramToken, "Telegram bot token")
	}
	if s.RESTEnabled && s.RESTKeyEnv != "" {
		add(s.RESTKeyEnv, "REST API authentication key")
	}
	return vars
}

// collectAndSetEnvVars prompts the user for each required env var value and
// sets it in the current process and persists it to the OS. Values are never
// passed through the LLM engine, audit logger, or any persistence layer.
// When stdin is a terminal, secret values are read without echoing.
func collectAndSetEnvVars(summary *BootstrapSummary, scanner *bufio.Scanner, stdout io.Writer) error {
	vars := requiredEnvVars(summary)
	if len(vars) == 0 {
		return nil
	}

	isTTY := term.IsTerminal(int(os.Stdin.Fd()))

	fmt.Fprintln(stdout, "\n--- Environment Variable Setup ---")
	fmt.Fprintln(stdout, "Enter values for the required environment variables below.")
	fmt.Fprintln(stdout, "Press Enter to skip any variable you want to set manually later.")
	if isTTY {
		fmt.Fprintln(stdout, "Your input is hidden for security — type your key and press Enter.")
	}
	fmt.Fprintln(stdout)

	anySkipped := false

	for _, v := range vars {
		fmt.Fprintf(stdout, "Enter your %s (%s) (or press Enter to skip): ", v.Purpose, v.Name)

		var value string
		if isTTY {
			raw, err := term.ReadPassword(int(os.Stdin.Fd()))
			fmt.Fprintln(stdout) // ReadPassword doesn't print newline
			if err != nil {
				return fmt.Errorf("read password for %s: %w", v.Name, err)
			}
			value = strings.TrimSpace(string(raw))
		} else {
			if !scanner.Scan() {
				return fmt.Errorf("unexpected end of input")
			}
			value = strings.TrimSpace(scanner.Text())
		}

		if value == "" {
			fmt.Fprintf(stdout, "  Skipped %s. You will need to set it manually before restarting.\n", v.Name)
			anySkipped = true
			continue
		}

		// Set in current process.
		if err := os.Setenv(v.Name, value); err != nil {
			return fmt.Errorf("setenv %s: %w", v.Name, err)
		}

		// Persist to OS.
		if err := persistEnvVar(v.Name, value); err != nil {
			fmt.Fprintf(stdout, "  Set %s in current session, but could not persist: %v\n", v.Name, err)
		} else {
			fmt.Fprintf(stdout, "  Set %s ✓\n", v.Name)
		}
	}

	fmt.Fprintln(stdout)
	if anySkipped {
		fmt.Fprintln(stdout, "If you provided all keys above, GoGoClaw is ready to use now. If you skipped any, set them manually and restart.")
	} else {
		fmt.Fprintln(stdout, "All environment variables set. GoGoClaw is ready to use.")
	}
	return nil
}

// persistEnvVar saves an environment variable to ~/.gogoclaw/env (KEY=value
// format, one per line, permissions 0600). On Windows, also calls setx for
// system-wide persistence.
func persistEnvVar(name, value string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("home dir: %w", err)
	}
	envPath := filepath.Join(home, ".gogoclaw", "env")

	// Read existing lines, replace if key already exists.
	var lines []string
	if data, err := os.ReadFile(envPath); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			if eqIdx := strings.IndexByte(line, '='); eqIdx > 0 {
				if line[:eqIdx] == name {
					continue // skip old value, we'll append new one
				}
			}
			lines = append(lines, line)
		}
	}
	lines = append(lines, fmt.Sprintf("%s=%s", name, value))
	content := strings.Join(lines, "\n") + "\n"

	if err := atomicWriteFile(envPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("write env file: %w", err)
	}

	// On Windows, also persist via setx for system-wide availability.
	if runtime.GOOS == "windows" {
		_ = exec.Command("cmd", "/C", "setx", name, value).Run()
	}
	return nil
}

// LoadEnvFile reads ~/.gogoclaw/env (KEY=value lines) and sets each as an
// environment variable via os.Setenv. Call this at process start before
// config loading.
func LoadEnvFile(configDir string) {
	envPath := filepath.Join(configDir, "env")
	data, err := os.ReadFile(envPath)
	if err != nil {
		return // file doesn't exist yet, that's fine
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eqIdx := strings.IndexByte(line, '=')
		if eqIdx <= 0 {
			continue
		}
		key := line[:eqIdx]
		val := line[eqIdx+1:]
		if os.Getenv(key) != "" {
			log.Printf("env: %s already set in environment, skipping env file value", key)
			continue
		}
		os.Setenv(key, val)
	}
}

// validateBootstrapConfig reloads the generated config and checks that it has
// at least one provider, base.yaml has system_prompt_file set, and enabled
// channels have their required env vars present.
func validateBootstrapConfig(configDir string, summary *BootstrapSummary, stdout io.Writer) error {
	cfg, err := config.NewLoader(configDir).Load()
	if err != nil {
		fmt.Fprintf(stdout, "Bootstrap validation failed: %v\n", err)
		fmt.Fprintln(stdout, "Config files were written but may have issues. Fix them and re-run GoGoClaw.")
		return fmt.Errorf("agent: bootstrap validation: %w", err)
	}
	if len(cfg.Providers) == 0 {
		msg := "no providers configured after bootstrap"
		fmt.Fprintf(stdout, "Bootstrap validation failed: %s\n", msg)
		return fmt.Errorf("agent: bootstrap validation: %s", msg)
	}
	if ac, ok := cfg.Agents["base"]; !ok || ac.SystemPromptFile == "" {
		msg := "base agent missing system_prompt_file"
		fmt.Fprintf(stdout, "Bootstrap validation failed: %s\n", msg)
		return fmt.Errorf("agent: bootstrap validation: %s", msg)
	}
	if cc, ok := cfg.Channels["telegram"]; ok && cc.Enabled {
		tokenEnv := cc.TokenEnv
		if tokenEnv != "" && os.Getenv(tokenEnv) == "" {
			fmt.Fprintf(stdout, "Warning: Telegram enabled but %s is not set.\n", tokenEnv)
		}
	}
	if cc, ok := cfg.Channels["rest"]; ok && cc.Enabled {
		keyEnv := cc.APIKeyEnv
		if keyEnv != "" && os.Getenv(keyEnv) == "" {
			fmt.Fprintf(stdout, "Warning: REST API enabled but %s is not set.\n", keyEnv)
		}
	}
	return nil
}

// atomicWriteFile writes data to path atomically by writing to a temp file
// first, then renaming. On Windows, removes destination before rename.
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".tmp-*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("close temp: %w", err)
	}
	if err := os.Chmod(tmpName, perm); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("chmod temp: %w", err)
	}

	// On Windows, os.Rename fails if destination exists.
	if runtime.GOOS == "windows" {
		os.Remove(path)
	}
	if err := os.Rename(tmpName, path); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("rename %s -> %s: %w", tmpName, path, err)
	}
	return nil
}

// extractDomain returns the hostname from a URL string.
func extractDomain(rawURL string) string {
	u, err := url.Parse(rawURL)
	if err != nil {
		return ""
	}
	return u.Hostname()
}
